### ISSUE TITLE
Integrating login/signup

### ISSUE THREAD

**Issue by Anu-Asok** [dynamic-learning/next-client#102]
Task 1:
- Call the login GraphQL API when login form is submitted which will return the below object:
`{userId, token, tokenExpiration, type}`
- Set the cookie with the received token.

Task 2:
- Call the signup GraphQL API when signup form is submitted which will return the below object:
`{_id, email, type}`

TODO:
- Finding a design to attach the auth token with GraphQL API calls.
- Updating a state variable using useHook which indicates whether the user is authenticated/admin & render accordingly.

**Comment by JithinKS97** [comment]
@anandsimmy @Aswin40 
These are the rendering changes that we need

**Index page (Workbook editor)** (pages/index.tsx)

1. In the file dropdown, show the **open menu** only if the user is authenticated
2. In the App menu, hide the **Signup and Login menu** If the user is authenticated
3. If the user is not authenticated and he clicks the **save button** in the file, inform that it is allowed only if authenticated. If the user logins, save his previous work.

**Simulations repo page** (pages/simulations.tsx)

1. Show **Add sim button** only if the user is admin
2. Only the admin users should be shown the dialogue box to **edit the simulation**.

For these changes, assume that **useAuth** returns the info about authentication and type of user. That is
```
{ isAuthenticated, type } = useAuth()
// isAuthenticated can be true or false
// type can be "normal" or "admin"
```
After these changes, we need to also modify the test cases so that all of them pass.

Also, refer this issue for adjustments needed in the front end due to auth related API changes in backend
https://github.com/dynamic-learning/graphql-server/issues/18

**Comment by Aswin40** [comment]
@JithinKS97 I will have look into this part.

**Comment by Aswin40** [comment]
@Anu-Asok Is there endpoint that gives the current user information if the user is authenticated and returns an error if the user is not authenticated. So that we can use it in the `useAuth`hook to check the authentication of the user.

Like in the `useAuth` hook a an api call is made to the server that contains the token. The api returns with the relevant user information like user_id,email and type if the user is authenticated. Otherwise return an error.

**Comment by JithinKS97** [comment]
@Aswin40 For now, will you be able to mock that API. The API is ready. But its not yet merged to dev. If you want, you can run the API locally and get access to them.

**Comment by Aswin40** [comment]
The type,userId,token does not change after a login right? Can we use cookies to store these values. Thoughts @Anu-Asok @JithinKS97 @anandsimmy

**Comment by JithinKS97** [comment]
Isn't that the only way we could do this?

**Comment by Aswin40** [comment]
@JithinKS97 There are some options 

1. Pass down the props from the obtained  useAuth hook. (may result in prop drilling)
2. Use redux store (I am not sure about the volatility)
3. Store them in cookies (only updated via login or explicit update of cookies)

**Comment by JithinKS97** [comment]
Is it possible to do this? In whatever component we require authentication
and authorization details, we will use the useAuth hook.

The useAuth hook will take care of accessing the cookies or whatever action
that needs to be done to expose isAuthenticated, type of user to the
component. (I guess the component need not know about the token)

In that way, we will not use the cookie access logic anywhere else.

I think the only place we might need to access the cookie directly will be
the API interceptor function.

Please let me know what you think.

**Comment by Aswin40** [comment]
My only concern is that, we can make use of the useAuth hook at a page level but still the child components need to get access to these details like who is admin and who is a normal user. The token may not be needed. In that case we may need to pass down the type props several levels down which is quite unnecessary. Can we think of some other alternative solution(other than cookie).

**Comment by JithinKS97** [comment]
What is the problem in using useAuth hook in child component also?

**Comment by Aswin40** [comment]
useAuth component is supposed to make an API call and check whether the user currently has authentication or not. if we use such a hook in child components the number of API calls will be quite high.
